services:
    _defaults:
        autowire: true
        autoconfigure: true

    Inachis\Fauna\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Entity/'
